import numpy as np
#Life w/o numpy to life with numpy

##Setup 1
#a=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Use python's built in functionality/operators to determine the following:
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

#Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

#Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

#Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

#Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

#Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

#Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

#Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.



In [117]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(a)
sum_of_a
sum(a)

55

In [120]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
min_of_a
min(a)

1

In [121]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
max_of_a
max(a)

10

In [126]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
mean_of_a

sum(a) / len(a)

5.5

In [140]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in 
#the above list together
product_of_a = np.prod(a)

product_of_a


total = 1

for x in a:
    total *= x
print(total)

product_of_a

3628800


3628800

In [33]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like 
#[1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = np.array(a)

odds_in_a = odds_in_a[odds_in_a % 2 == 1]

odds_in_a

array([1, 3, 5, 7, 9])

In [91]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = np.array(a)

evens_in_a = evens_in_a[evens_in_a % 2 == 0]

evens_in_a

array([ 2,  4,  6,  8, 10])

##What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
##Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, 
#and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

#Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

#Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

#Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


#Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

#Exercise 5 - refactor the following to use numpy for calculating the product of all numbers 
#multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

#Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


#Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


#Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

#Exercise 9 - print out the shape of the array b.

#Exercise 10 - transpose the array b.

#Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

#Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [92]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [97]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

#turn b variable into numpy array
b = np.array(b)

#assign np.sum(b, axis=1) to sum_of_b variable. (b represents the array, axis=1 says sum each array separately)
sum_of_b = np.sum(b, axis=1)

#call sum_of_b to get your two sums
sum_of_b

array([12, 21])

In [100]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

#turn b variable into numpy array
b = np.array(b)

#assign np.min(b, axis=1) function to min_of_b. Gets the min of each array 
min_of_b = np.min(b, axis=1)
#call the variable to get your output
min_of_b

array([3, 6])

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

#turn b variable into numpy array
b = np.array(b)
#assign np.max(b, axis=1) to variable max_of_b
max_of_b = np.max(b, axis=1)

#call variable
max_of_b

In [102]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = np.mean(b, axis=1)

mean_of_b

array([4., 7.])

In [129]:
###### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers 
#multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
product_of_b = np.product(b)

product_of_b

20160

In [110]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

squares_of_b = np.square(b)

squares_of_b
        
        

array([[ 9, 16, 25],
       [36, 49, 64]])

In [115]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
odds_in_b = b[b%2==1]
odds_in_b

array([3, 5, 7])

In [116]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
evens_in_b = b[b%2==0]

evens_in_b

array([4, 6, 8])

In [130]:
# Exercise 9 - print out the shape of the array b.
b.shape

(2, 3)

In [132]:
# Exercise 10 - transpose the array b.
b.T
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [133]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)


array([[3, 4, 5, 6, 7, 8]])

In [134]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

# Exercise 2 - Determine the standard deviation of c.

# Exercise 3 - Determine the variance of c.

# Exercise 4 - Print out the shape of the array c

# Exercise 5 - Transpose c and print out transposed result.

# Exercise 6 - Get the dot product of the array c with c. 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [137]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to 
#using numpy array methods.

# Exercise 1 - Find the min, max, sum, and product of c.
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)
c



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
# Exercise 1 - Find the min, max, sum, and product of c.
c.min(), c.max(), c.prod()

(1, 9, 362880)

In [146]:
# Exercise 2 - Determine the standard deviation of c.
b = c.std()
np.round(b,2)

2.58

In [149]:
# Exercise 3 - Determine the variance of c.
c.var().round(2)

6.67

In [150]:
# Exercise 4 - Print out the shape of the array c
c.shape


(3, 3)

In [153]:
# Exercise 5 - Transpose c and print out transposed result.
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [155]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [156]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(c * c.T).sum()


261

In [157]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [159]:
c * c.T

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [160]:
(c * c.T).prod()

131681894400

In [162]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)
d

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [163]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [166]:
# Exercise 2 - Find the cosine of all the numbers in dnp.cos(d)
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [167]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [168]:
# Exercise 4 - Find all the negative numbers in d
d [d < 0]

array([-90, -30, -45, -45])

In [169]:
# Exercise 5 - Find all the positive numbers in d
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [170]:
# Exercise 6 - Return an array of only the unique numbers in d.
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [171]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [172]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [173]:
# Exercise 8 - Print out the shape of d.
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [174]:
d.shape

(3, 6)

In [176]:
# Exercise 9 - Transpose and then print out the shape of d.
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [178]:
d.T.shape

(6, 3)

In [179]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])