In [21]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [34]:
#How many negative numbers are there
#4
num = a < 0
num

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [37]:
#How many positive numbers are there?
#5
num = a > 0
num

array([[ True,  True,  True,  True, False, False, False, False, False,
        False,  True, False]])

In [38]:
#How many even positive numbers are there?
#8
num = a % 2 == 0
num

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True, False, False])

In [41]:
#If you were to add 3 to each data point, how many positive numbers would there be?
#10
num = (a + 3) > 0
num

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False])

In [58]:
#If you squared each number, what would the new mean and standard deviation be?
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [59]:
#squared each value in num
num = a ** 2
num

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [60]:
#mean value
np.mean(num)

74.0

In [61]:
#standard diviation array elements
np.std(num)
std_num = np.std(num)
np.round(std_num, 2)

144.02

In [65]:
####Centering####

#original array below
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [66]:
np.mean(a)

3.0

In [62]:
# created function to center data
center_function = lambda x: x - x.mean()

In [63]:
# apply created center function to numpy array 
data_centered = center_function(a)

In [64]:
#view the updated array
print(data_centered)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [67]:
#verify the mean of the centered array is 0
print(data_centered.mean())

0.0


In [78]:
#Calculate the z-score for each data point. Recall that the z-score is given by: Z = (x - μ) / σ
#Calculate z-score of one dimensional numpy array

import pandas as pd
import numpy as np
import scipy.stats as stats

#create your np array
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#puts the array in order asc
a.sort()

#use function stats.zscore(a) by passing in your variable a 
stats.zscore(a)

#each z-score tells us how many standard deviations away an individual value is from the mean.


array([-1.24034735, -1.11631261, -0.62017367, -0.49613894, -0.3721042 ,
       -0.3721042 , -0.3721042 ,  0.        ,  0.12403473,  0.86824314,
        1.11631261,  2.48069469])

In [79]:
####Multi-Dimensional Arrays####

#If we have a multi-dimensional array, we can use the axis parameter 
#to specify that we want to calculate each z-score relative to its own array

data = np.array([[5, 6, 7, 7, 8],
                 [8, 8, 8, 9, 9],
                 [2, 2, 4, 4, 5]])

In [80]:
#We can use the following syntax to calculate the z-scores for each array
stats.zscore(data, axis=1)

#The z-scores for each individual value are shown relative to the array they’re in

array([[-1.56892908, -0.58834841,  0.39223227,  0.39223227,  1.37281295],
       [-0.81649658, -0.81649658, -0.81649658,  1.22474487,  1.22474487],
       [-1.16666667, -1.16666667,  0.5       ,  0.5       ,  1.33333333]])