import numpy as np
#Life w/o numpy to life with numpy

##Setup 1
#a=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Use python's built in functionality/operators to determine the following:
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

#Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

#Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

#Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

#Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

#Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

#Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

#Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.



In [3]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(a)
sum_of_a

55

In [5]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
min_of_a

1

In [7]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
max_of_a

10

In [9]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
mean_of_a

5.5

In [32]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in 
#the above list together
product_of_a = np.multiply(a, a)

product_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [33]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like 
#[1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = np.array(a)

odds_in_a = odds_in_a[odds_in_a % 2 == 1]

odds_in_a

array([1, 3, 5, 7, 9])

In [91]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = np.array(a)

evens_in_a = evens_in_a[evens_in_a % 2 == 0]

evens_in_a

array([ 2,  4,  6,  8, 10])

In [ ]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, 
#and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers 
#multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

# Exercise 9 - print out the shape of the array b.

# Exercise 10 - transpose the array b.

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [92]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [97]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

#turn b variable into numpy array
b = np.array(b)

#assign np.sum(b, axis=1) to sum_of_b variable. (b represents the array, axis=1 says sum each array separately)
sum_of_b = np.sum(b, axis=1)

#call sum_of_b to get your two sums
sum_of_b

array([12, 21])

In [100]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

#turn b variable into numpy array
b = np.array(b)

#assign np.min(b, axis=1) function to min_of_b. Gets the min of each array 
min_of_b = np.min(b, axis=1)
#call the variable to get your output
min_of_b

array([3, 6])

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

#turn b variable into numpy array
b = np.array(b)
#assign np.max(b, axis=1) to variable max_of_b
max_of_b = np.max(b, axis=1)

#call variable
max_of_b

In [102]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = np.mean(b, axis=1)

mean_of_b

array([4., 7.])

In [106]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers 
#multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
product_of_b = np.multiply(b,b)

product_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [110]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

squares_of_b = np.square(b)

squares_of_b
        
        

array([[ 9, 16, 25],
       [36, 49, 64]])

In [115]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
odds_in_b = b[b%2==1]
odds_in_b

array([3, 5, 7])

In [116]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
evens_in_b = b[b%2==0]

evens_in_b

array([4, 6, 8])